@startuml
'https://plantuml.com/class-diagram

package Question {
    abstract class Question {
        + Answers : String[]
    }

    class MultipleChoice {
    }

    'class CheckboxChoice {'
    '}'

    Question <|-- MultipleChoice
    'Question <|-- CheckboxChoice'
}

class Survey {
    + Questions : Question[]
}

Survey *--"1..*" Question


package IO {
    interface IO {
        + read()
        + save()
    }

    class IOFile {
    }

    class IODatabase {
        + uploadSurvey()
        + getSurvey()
    }

    IO <|.. IOFile
    IO <|.. IODatabase
}

package UI {
    class UI {
        + uianswer : UIAnswer
        + uicreate : UICreate
    }

    interface UIAnswer {
        + UIShowAnswer()
    }

    interface UICreate {
        + UIShowCreate()
    }

    UI *-- UIAnswer
    UI *-- UICreate
    package UICommandLine {
        class UICommandLineAnswer {
        }
        class UICommandLineCreate {
        }
    }
    package UIJavaFX {
        class UIJavaFXAnswer {
        }
        class UIJavaFXCreate {
        }
    }
    UIAnswer <|.. UICommandLineAnswer
    UIAnswer <|.. UIJavaFXAnswer
    UICreate <|.. UICommandLineCreate
    UICreate <|.. UIJavaFXCreate
}

class Controller {
    + io : IO
    + ui : UI
    + survey : Survey
}

Controller -- Survey
Controller -- IO
Controller -- UI


@enduml